services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - ${POSTGRES_PORT}:5432
